### ISSUE TITLE
Is there any way to login to vault UI and enable RBAC

### ISSUE THREAD

**Issue by techs07** [puppetlabs/vault-plugin-secrets-oauthapp#9]
## Describe the Bug
I have followed the steps and created a custom provider. Though I am able to get the access code but I am not sure how to login to vault with the help of the code generated out of the redirected URL.
Apologies if i have asked the basic question.

## Expected Behaviour
I was looking around for some documentation for the vault login flow.
Is there any way to enable RBAC

## Steps to Reproduce
Steps to reproduce the behaviour:

## Environment
 - vault version 1.4.1
 - Platform: Kubernetes

**Comment by impl** [comment]
Hi @techs07,

I think you may want to use the [OIDC](https://learn.hashicorp.com/vault/identity-access-management/oidc-auth) auth plugin that ships with Vault rather than this one. This plugin allows you to store OAuth2 credentials for use in your application, but it isn't an authentication mechanism to provide access to Vault itself.

Let me know if you have any other questions/concerns! Thanks!
